source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LoginFramework_Example', :exclusive => true do
  pod 'LoginFramework', :path => '../'
end

target 'LoginFramework_Tests', :exclusive => true do
  pod 'LoginFramework', :path => '../'

  pod 'FBSnapshotTestCase'
end
